### ISSUE TITLE
Dubbo-go Metrics 指标开发计划与任务分解

### ISSUE THREAD

**Issue by ev1lQuark** [apache/dubbo-go#2315]
## 最终目标：
Dubbo-go 核心代码指标全面对齐 [Dubbo 框架标准监控指标](https://cn.dubbo.apache.org/zh-cn/overview/reference/metrics/standard_metrics/)

## 任务规划：

如果有对于可观测性 Mertrics 开发感兴趣的朋友，可以在本 Issue 下留言钉钉号+任务子项。欢迎大家参与 dubbo-go 开源社区的开发！

### Provider-Consumer RPC 调用过程
- [ ]  [Provider](https://cn.dubbo.apache.org/zh-cn/overview/reference/metrics/standard_metrics/#provider-metrics) 及 [Consumer](https://cn.dubbo.apache.org/zh-cn/overview/reference/metrics/standard_metrics/#consumer-metrics)
- [ ]    [Provider Exception](https://cn.dubbo.apache.org/zh-cn/overview/reference/metrics/standard_metrics/#provider-exception) 及 [Consumer Exception](https://cn.dubbo.apache.org/zh-cn/overview/reference/metrics/standard_metrics/#consumer-exception)

### 三大中心及 Go 运行时
- [ ]  [注册中心](https://cn.dubbo.apache.org/zh-cn/overview/reference/metrics/standard_metrics/#consumer-exception)
- [ ]  [元数据中心](https://cn.dubbo.apache.org/zh-cn/overview/reference/metrics/standard_metrics/#metadata-center-metrics)
- [ ]  [配置中心](https://cn.dubbo.apache.org/zh-cn/overview/reference/metrics/standard_metrics/#metadata-center-metrics)、[应用信息](https://cn.dubbo.apache.org/zh-cn/overview/reference/metrics/standard_metrics/#applicationinfo)、[Go 运行时](https://cn.dubbo.apache.org/zh-cn/overview/reference/metrics/standard_metrics/#threadpool-metrics)

---

## Ultimate Goal:
Dubbo-go core code aligns comprehensively with [Dubbo framework standard monitoring metrics](https://cn.dubbo.apache.org/zh-cn/overview/reference/metrics/standard_metrics/).

## Task Planning:
If you are interested in developing observable metrics, please leave a message with your DingTalk ID and task item details in this issue. Welcome everyone to participate in the development of the Dubbo-go open-source community!

### Provider-Consumer RPC Call Process:
- [Provider](https://cn.dubbo.apache.org/zh-cn/overview/reference/metrics/standard_metrics/#provider-metrics) and [Provider Exception](https://cn.dubbo.apache.org/zh-cn/overview/reference/metrics/standard_metrics/#provider-exception)
- [Consumer](https://cn.dubbo.apache.org/zh-cn/overview/reference/metrics/standard_metrics/#consumer-metrics) and [Consumer Exception](https://cn.dubbo.apache.org/zh-cn/overview/reference/metrics/standard_metrics/#consumer-exception)

### Three Core Centers and Go Runtime:
- [Registry Center](https://cn.dubbo.apache.org/zh-cn/overview/reference/metrics/standard_metrics/#consumer-exception)
- [Metadata Center](https://cn.dubbo.apache.org/zh-cn/overview/reference/metrics/standard_metrics/#metadata-center-metrics)
- [Configuration Center](https://cn.dubbo.apache.org/zh-cn/overview/reference/metrics/standard_metrics/#metadata-center-metrics), [Application Information](https://cn.dubbo.apache.org/zh-cn/overview/reference/metrics/standard_metrics/#applicationinfo), [Go Runtime](https://cn.dubbo.apache.org/zh-cn/overview/reference/metrics/standard_metrics/#threadpool-metrics)

**Comment by chickenlj** [comment]
[期望的终态运行效果](https://cn.dubbo.apache.org/zh-cn/overview/core-features/observability/#metrics)

**Comment by FinalT** [comment]
I am interested in Registry Center

**Comment by barnettZQG** [comment]
@ev1lQuark 很赞的需求，另外有一个建议。将 Metrics 模块的被集成能力加强。目前只能启动 dubbo-go 实现的http server 拿到metric。希望可以支持从外部注入 Prometheus Registerer。如果认同，我可以贡献开发。

**Comment by ev1lQuark** [comment]
> 

上次双周会讨论了 dubbo-go 作为微服务架构开发框架的定位，社区对于框架的“被集成”能力持较为保守的态度，建议您可以提一个新 issue

**Comment by ev1lQuark** [comment]
> @ev1lQuark 很赞的需求，另外有一个建议。将 Metrics 模块的被集成能力加强。目前只能启动 dubbo-go 实现的http server 拿到metric。希望可以支持从外部注入 Prometheus Registerer。如果认同，我可以贡献开发。

上次双周会讨论了 dubbo-go 作为微服务架构开发框架的定位，社区对于框架的“被集成”能力持较为保守的态度，建议您可以提一个新 issue

**Comment by FoghostCn** [comment]
> @ev1lQuark 很赞的需求，另外有一个建议。将 Metrics 模块的被集成能力加强。目前只能启动 dubbo-go 实现的http server 拿到metric。希望可以支持从外部注入 Prometheus Registerer。如果认同，我可以贡献开发。

metric 模块目前已经大致可用来，从某种意义上来说，你这个需求其实可以实现的，目前的 Prometheus registry 实现是需要传入 Registerer 的只不过目前用的默认的 Registerer，用户是可以扩展覆盖掉原始配置的
