### ISSUE TITLE
Summarized todos for #2441

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo-go#2442]
This issue is a collection of todos extracted from https://github.com/apache/dubbo-go/issues/2441

- [ ] Find a better name for `global` package, possible names 'cfg' , 'gConfig', `_global`, etc.
- [x] Move `XxxOption` definition in global package to separate packages https://github.com/apache/dubbo-go/issues/2446
  - [x] protocol
  - [x] registry
  - [x] metrics
  - [x] config-center
  - [x] metadata
  - [x] logger
  - [x] metrics & tracing
  - [x] tls, custom, and profile will not be supported in the first release
- [x] Decide params that should be put in CallOption, timeout, and more? https://github.com/apache/dubbo-go/issues/2448
   - [x] timeout
   - [x] retries
   - [x] xxx?
- [ ] Examine properties in various Configs, like `ServerOption.FilterConf`, etc.
- [ ] Mechanism for passing extra headers and trailers #2435
- [ ] Completely delete `dubbo3` and `grpc` packages
- [ ] RefreshService? reflectionService and healthService
- [x] Simplified version of `dubbo.WithRegistry()`, with default key support.  https://github.com/apache/dubbo-go/issues/2444
- [x] Unify naming of `server.WithRegistry(id, ...)` and `server.WithRegistryIds()` https://github.com/apache/dubbo-go/issues/2444

**Comment by chickenlj** [comment]
https://github.com/apache/dubbo-go/issues/2443
